USE codeup_test_db;

INSERT INTO albums (artists, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 47.3, 'Pop, post-disco, funk, rock'),
       ('AC/DC', 'Back in Black', 1980, 29.4, 'Hard Rock'),
       ('Meat Load', 'Bat Out Of Hell', 1977, 21.7, 'Hard rock, Glam Rock, Progressive Rock'),
       ('Pink Floyd', 'The Dark Side Of the Moon', 1973, 24.4, 'Progressive Rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 28.4, 'R&B, Soul, Pop, Soundtrack'),
       ('Eagles', 'Their Greatest hits(1971-1975)', 1976, 41.2, 'Country Rock, Soft Rock, Folk Rock'),
       ('Bee Gees', 'Saturday Night Fever', 1977, 21.6, 'Disco'),
       ('Fleetwood Mac', 'Rumors', 1977, 27.9, 'Soft Rock'),
       ('Shania Twain', 'Come On Over', 1997, 29.6, 'Country, Pop'),
       ('Various Artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 14.4, 'Rock and Roll'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 29, 'Hard Rock, Heavy Metal, Funk and Rock'),
       ('Michael Jackson', 'Bad', 1987, 22.2, 'Pop, Rhythm and Blues, Funk, Rock'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 24.4, 'Alternative Rock'),
       ('Michael Jackson', 'Dangerous', 1991, 17, 'New Jack Swing, R&B, Pop'),
       ('Celine Dion', 'Falling Into you', 1996, 21.2, 'Pop, Soft Rock'),
       ('Eagles', 'Hotel California', 1976, 31.5, 'Soft Rock'),
       ('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', 1967, 18.2, 'Rock'),
       ('Various Artists', 'Dirty Dancing', 1987, 17.9, 'Pop, Rock, R&B'),
       ('Adele', '21', 2011, 30.8, 'Pop, Soul'),
       ('Madonna', 'The Immaculate Collection', 1990, 19.4, 'Pop, Dance'),
       ('Celine Dion', 'Lets Talk About it', 1997, 19.3, 'Pop, Soft Rock'),
       ('Metallica', 'Metallica', 1991, 25.2, 'Heavy Metal'),
       ('The Beatles', '1', 2000, 23.4, 'Rock'),
       ('The Beatles', 'Abbey Road', 1969, 14.4, 'Rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 23, 'Pop, Disco'),
       ('Bruce Springston', 'Born in The U.S.A.', 1984, 19.6, 'Heartland Rock'),
       ('Pink Floyd', 'The Wall', 1979, 18.7, 'Progressive Rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'FIlm Score'),
       ('Dire Straits', 'Brothers in Arms', 1985, 17.7, 'Roots rock, Blues rock, Soft rock'),
       ('Nirvana', 'NeverMind', 1991, 16.7, 'Grunge, Alternative Rock'),
       ('Santana', 'Supernatural', 1999, 20.5, 'Latin Rock'),
       ('Guns N Roses', 'Appetite for Destruction', 1987, 21.9, 'Hard Rock'),
       ('Elton John', 'Goodbye Yellow Brick Road', 1973, 8.5, 'Rock, Pop Rock, Glam Rock');
